table 'Gediplomeerden naar Geslacht'
	lineageTag: b38606bd-aead-4bc8-9d28-e474428709d8

	measure 'Totaal Gediplomeerden (Geslacht)' = SUM('Gediplomeerden naar Geslacht'[Aantal Gediplomeerden])
		formatString: #,0
		lineageTag: 3bc0d71f-d712-4652-8b90-4047a3eb9062

	column ID
		dataType: int64
		isHidden
		lineageTag: 69865e22-9b1d-4645-ae59-9ed2cfb40433
		summarizeBy: none
		sourceColumn: id

	column 'Tijd Key'
		dataType: int64
		isHidden
		lineageTag: f6582915-dc59-4e47-9a69-7d6be2365021
		summarizeBy: none
		sourceColumn: tijd_key

	column 'Instelling Key'
		dataType: int64
		isHidden
		lineageTag: 4fed7389-3a3a-4d22-8b4a-67f42d67b0e8
		summarizeBy: none
		sourceColumn: instelling_key

	column 'Sector Key'
		dataType: int64
		isHidden
		lineageTag: 16c2ff39-b6b5-4989-8b3d-0f686d2f031e
		summarizeBy: none
		sourceColumn: sector_key

	column 'Geografie Key'
		dataType: int64
		isHidden
		lineageTag: 7b497ef3-d90c-4bd6-90ff-d8e2ae1cf4ec
		summarizeBy: none
		sourceColumn: geografie_key

	column 'Soort Diploma Key'
		dataType: int64
		isHidden
		lineageTag: 49656c82-7048-41a4-9522-3d76f057b728
		summarizeBy: none
		sourceColumn: soort_diploma_key

	column 'Geslacht Key'
		dataType: int64
		isHidden
		lineageTag: 5f1da7dc-2b70-452d-af5e-b1e34d5265c8
		summarizeBy: none
		sourceColumn: geslacht_key

	column 'Aantal Gediplomeerden'
		dataType: int64
		lineageTag: d975c923-4bcb-4689-9b37-80b27b2900dc
		summarizeBy: sum
		sourceColumn: aantal_gediplomeerden

	column 'Privacy Onderdrukt'
		dataType: boolean
		lineageTag: e12de361-9fca-4258-9ce5-8f036a1f739e
		summarizeBy: none
		sourceColumn: is_onderdrukt

	partition 'Gediplomeerden naar Geslacht' = m
		mode: import
		queryGroup: Feiten
		source =
				let
					    Source = Parquet.Document(File.Contents("D:/HogeschoolUtrecht/GithubRepos/ai-dimensional-modal-agent/data/processed/feit_gediplomeerden_geslacht.parquet"))
					in
					    Source

