table 'Measures DM'
	lineageTag: e7a3a361-12f8-49c1-a05f-c394db371957

	measure 'Totaal Inschrijvingen (Geslacht)' = SUM('Inschrijvingen naar Geslacht'[Aantal Inschrijvingen])
		formatString: 0
		lineageTag: 930df94e-d9ac-4675-bc8b-249e49b2aa83

	partition 'Measures DM' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	changedProperty = Name

	annotation PBI_ResultType = Table

