table 'Measures DM'
	lineageTag: a5ddc1e8-0d05-4194-a2ad-047aed20398e

	column Column1
		dataType: string
		lineageTag: 2bec79dd-d5d5-48b2-8bdb-92fb68286549
		isHidden
		summarizeBy: none

	measure 'Totaal Ingeschrevenen' = SUM('Ingeschrevenen'[Aantal Ingeschrevenen])
		formatString: "#,0"
		lineageTag: df62261d-db78-45be-b986-ce7dcf014bf0

	measure '% Privacy Onderdrukt' = DIVIDE(COUNTROWS(FILTER('Ingeschrevenen', 'Ingeschrevenen'[Privacy Onderdrukt])), COUNTROWS('Ingeschrevenen'))
		formatString: "0.00%"
		lineageTag: 761f8bd3-2968-45c3-b406-ad9d7eb4d663

	measure 'Totaal Inschrijvingen' = SUM('Inschrijvingen'[Aantal Inschrijvingen])
		formatString: "#,0"
		lineageTag: 2ccdcbc6-9aad-42c0-bc44-614a642e4359

	measure 'Totaal Eerstejaars' = SUM('Eerstejaars'[Aantal Eerstejaars])
		formatString: "#,0"
		lineageTag: 31d1ec31-d43e-4881-8cd9-ad240a2ea56e

	measure 'Totaal Gediplomeerden' = SUM('Gediplomeerden'[Aantal Gediplomeerden])
		formatString: "#,0"
		lineageTag: e37a2494-3a69-48bd-aae6-1a45496869bb

	measure 'Totaal Ingeschrevenen (Geslacht)' = SUM('Ingeschrevenen naar Geslacht'[Aantal Ingeschrevenen])
		formatString: "#,0"
		lineageTag: 2f12c71f-49c8-40f6-a044-cef5f8c3bee9

	measure 'Totaal Inschrijvingen (Geslacht)' = SUM('Inschrijvingen naar Geslacht'[Aantal Inschrijvingen])
		formatString: "#,0"
		lineageTag: 9f52016c-1d39-437e-9bc2-4f7420b5208d

	measure 'Totaal Eerstejaars (Geslacht)' = SUM('Eerstejaars naar Geslacht'[Aantal Eerstejaars])
		formatString: "#,0"
		lineageTag: ba330d8e-423e-473d-a918-8ec977ef30c4

	measure 'Totaal Gediplomeerden (Geslacht)' = SUM('Gediplomeerden naar Geslacht'[Aantal Gediplomeerden])
		formatString: "#,0"
		lineageTag: 8616a17b-9731-40bd-96c5-48dc77e1dd25

	measure 'Totaal Ingeschrevenen (Oplvorm)' = SUM('Ingeschrevenen naar Opleidingsvorm'[Aantal Ingeschrevenen])
		formatString: "#,0"
		lineageTag: 93fc2850-553c-47c7-9689-0c95ef590f89

	measure 'Totaal Inschrijvingen (Oplvorm)' = SUM('Inschrijvingen naar Opleidingsvorm'[Aantal Inschrijvingen])
		formatString: "#,0"
		lineageTag: f50f7c2e-e83d-41d3-ad87-069b6cf19c55

	measure 'Totaal Eerstejaars (Oplvorm)' = SUM('Eerstejaars naar Opleidingsvorm'[Aantal Eerstejaars])
		formatString: "#,0"
		lineageTag: 07c692c7-7fd1-4fcf-9b07-796736793b0b

	measure 'Totaal Gediplomeerden (Oplvorm)' = SUM('Gediplomeerden naar Opleidingsvorm'[Aantal Gediplomeerden])
		formatString: "#,0"
		lineageTag: 28571801-7c3a-4254-a0cc-fad31fca4413

	partition 'Measures DM' = m
		mode: import
		source = ```
			let
			    Source = Table.FromRows({{""}}, {"Column1"})
			in
			    Source
		```
